export const services = {
  property: {
    title: 'Property Advisory',
    description: 'Expert guidance on residential and commercial property investments in New Zealand.',
    icon: '🏠',
  },
  businessInvestment: {
    title: 'Business Investment',
    description: 'Find and invest in profitable businesses across New Zealand.',
    icon: '💼',
  },
  jobsManpower: {
    title: 'Jobs & Manpower',
    description: 'Recruitment services connecting businesses with skilled workers.',
    icon: '👥',
  },
  medicalTourism: {
    title: 'Medical Tourism',
    description: 'Access world-class healthcare in New Zealand.',
    icon: '🏥',
  },
}

export const businessTypes = [
  {
    id: 'petrol-stations',
    name: 'Petrol Stations',
    description: 'Stable, cash-flow positive businesses with consistent demand.',
    priceRange: 'NZD $500,000 - $3,000,000+',
    suitableFor: 'Hands-on operators and passive investors',
    highlights: [
      'Consistent daily cash flow',
      'Prime location advantages',
      'Established customer base',
      'Multiple revenue streams (fuel, convenience items)',
    ],
  },
  {
    id: 'motels-hotels',
    name: 'Motels & Hotels',
    description: 'Tourism-driven hospitality businesses in prime New Zealand locations.',
    priceRange: 'NZD $800,000 - $5,000,000+',
    suitableFor: 'Hospitality entrepreneurs and tourism investors',
    highlights: [
      'Tourism industry growth',
      'Seasonal and year-round demand',
      'Property appreciation potential',
      'Diverse revenue streams',
    ],
  },
  {
    id: 'liquor-stores',
    name: 'Liquor Stores',
    description: 'Profitable retail businesses with strong local market presence.',
    priceRange: 'NZD $300,000 - $1,500,000+',
    suitableFor: 'Retail operators and local business investors',
    highlights: [
      'High-margin products',
      'Local community focus',
      'Regulated market stability',
      'Established supplier relationships',
    ],
  },
  {
    id: 'grocery-supermarkets',
    name: 'Grocery / Supermarkets',
    description: 'Essential retail businesses serving local communities.',
    priceRange: 'NZD $400,000 - $2,500,000+',
    suitableFor: 'Retail operators and community-focused investors',
    highlights: [
      'Essential service business',
      'Consistent customer traffic',
      'Diverse product range',
      'Community integration opportunities',
    ],
  },
  {
    id: 'restaurants-cafes',
    name: 'Restaurants & Cafés',
    description: 'Culinary businesses in New Zealand\'s vibrant food scene.',
    priceRange: 'NZD $200,000 - $1,200,000+',
    suitableFor: 'Chef-entrepreneurs and hospitality enthusiasts',
    highlights: [
      'Creative business opportunities',
      'Strong local food culture',
      'Tourism and local customer base',
      'Brand building potential',
    ],
  },
  {
    id: 'bars-gaming',
    name: 'Bars & Gaming',
    description: 'Entertainment venues with gaming and hospitality revenue.',
    priceRange: 'NZD $600,000 - $2,500,000+',
    suitableFor: 'Hospitality operators with gaming experience',
    highlights: [
      'Dual revenue streams',
      'Evening and night trade',
      'Gaming license value',
      'Entertainment industry growth',
    ],
  },
  {
    id: 'kiwi-avocado-farms',
    name: 'Kiwi & Avocado Farms',
    description: 'Agricultural investments in New Zealand\'s premium export crops.',
    priceRange: 'NZD $1,000,000 - $10,000,000+',
    suitableFor: 'Agricultural investors and export-focused businesses',
    highlights: [
      'Export market opportunities',
      'Premium product positioning',
      'Long-term asset appreciation',
      'Sustainable farming practices',
    ],
  },
  {
    id: 'glass-stores',
    name: 'Glass Stores',
    description: 'Specialized retail and service businesses in glass products.',
    priceRange: 'NZD $250,000 - $1,000,000+',
    suitableFor: 'Trade-focused operators and service businesses',
    highlights: [
      'Specialized market niche',
      'Trade and retail customers',
      'Service and product sales',
      'Established trade relationships',
    ],
  },
  {
    id: 'salons',
    name: 'Salons',
    description: 'Beauty and personal care businesses serving local communities.',
    priceRange: 'NZD $150,000 - $800,000+',
    suitableFor: 'Beauty professionals and service business operators',
    highlights: [
      'Personal service business',
      'Recurring customer base',
      'Creative business environment',
      'Community-focused operations',
    ],
  },
]

export const whyNewZealand = [
  {
    title: 'Political Stability',
    description: 'Many countries worldwide offer stable political environments and transparent business regulations.',
  },
  {
    title: 'Quality of Life',
    description: 'World-class healthcare, education, and natural beauty make many destinations ideal places to live and work.',
  },
  {
    title: 'Business-Friendly',
    description: 'Supportive government policies, ease of doing business, and access to global markets.',
  },
  {
    title: 'Immigration Pathways',
    description: 'Various visa options for investors, entrepreneurs, and skilled workers worldwide.',
  },
]

export const whyChooseUs = [
  'Extensive network of business opportunities across New Zealand',
  'Deep understanding of NZ immigration and investment regulations',
  'Personalized guidance from initial inquiry to settlement',
  'Trusted relationships with sellers, agents, and legal professionals',
  'Proven track record helping migrants and investors succeed',
]

export const statistics = [
  {
    number: '500+',
    label: 'Successful Clients',
    icon: '👥',
  },
  {
    number: '15+',
    label: 'Years Experience',
    icon: '⭐',
  },
  {
    number: '200+',
    label: 'Businesses Sold',
    icon: '💼',
  },
  {
    number: '98%',
    label: 'Client Satisfaction',
    icon: '✨',
  },
]

export const testimonials = [
  {
    name: 'Steven',
    location: 'Auckland',
    image: '/images/steven.png',
    text: 'FBIS helped us find and purchase a petrol station in Auckland. Their guidance through the entire process was exceptional. Highly recommended!',
    rating: 5,
  },
  {
    name: 'Gurpreet Atwal',
    location: 'Wellington',
    image: '/images/Gurpreet atwal.png',
    text: 'As a migrant investor, I was unsure about NZ property regulations. The team provided expert advice and helped me secure a great commercial property.',
    rating: 5,
  },
]

export const processSteps = [
  {
    step: 1,
    title: 'Initial Consultation',
    description: 'We discuss your goals, budget, and requirements to understand your needs.',
    icon: '📞',
  },
  {
    step: 2,
    title: 'Opportunity Matching',
    description: 'We identify suitable properties or businesses that match your criteria.',
    icon: '🔍',
  },
  {
    step: 3,
    title: 'Due Diligence',
    description: 'Comprehensive analysis and verification of opportunities with our expert team.',
    icon: '📋',
  },
  {
    step: 4,
    title: 'Negotiation & Purchase',
    description: 'We handle negotiations and guide you through the purchase process.',
    icon: '🤝',
  },
  {
    step: 5,
    title: 'Settlement & Support',
    description: 'Ongoing support through settlement and beyond to ensure your success.',
    icon: '✅',
  },
]

export const propertyTypes = [
  {
    id: 'residential',
    name: 'Residential Property',
    description: 'Houses, flats, townhouses, and residential investments for families and investors.',
    priceRange: 'NZD $300,000 - $2,500,000+',
    examples: ['Houses', 'Flats', 'Townhouses', 'Apartments', 'Units'],
    highlights: [
      'Strong rental demand in major cities',
      'Capital appreciation potential',
      'Suitable for first-home buyers and investors',
      'Diverse options from suburban to urban',
      'Long-term wealth building',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'commercial',
    name: 'Commercial Property',
    description: 'Retail shops, offices, and commercial spaces in prime locations.',
    priceRange: 'NZD $500,000 - $5,000,000+',
    examples: ['Retail Shops', 'Office Buildings', 'Shopping Centers', 'Showrooms'],
    highlights: [
      'Attractive yields (5-8%)',
      'Long-term lease arrangements',
      'Prime location advantages',
      'Stable rental income',
      'Business integration opportunities',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'industrial',
    name: 'Industrial Property',
    description: 'Warehouses, factories, and industrial units for manufacturing and logistics.',
    priceRange: 'NZD $800,000 - $10,000,000+',
    examples: ['Warehouses', 'Factories', 'Distribution Centers', 'Industrial Units'],
    highlights: [
      'High yields (7-10%)',
      'Essential infrastructure',
      'Logistics hub locations',
      'Long-term tenant stability',
      'Scalable operations',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
]

export const propertyExampleListings = {
  residential: [
    {
      id: '145-albany-highway-albany',
      type: 'residential',
      title: '145 Albany Highway, Albany',
      location: 'Albany, North Shore City',
      priceRange: 'NZD $1,295,000',
      bedrooms: '4',
      bathrooms: '3',
      garage: '1',
      titleType: 'Freehold',
      listingNumber: '925100',
      listingDate: '2 December 2025',
      description:
        'Step into a world of elegance and sophistication with these brand new, beautifully designed townhouses – the perfect fusion of modern luxury and timeless charm, right in the heart of the North Shore.',
      details: [
        'Each home has been thoughtfully crafted for effortless living, featuring spacious, light-filled interiors, high-end finishes throughout, and seamless indoor-outdoor flow to a private deck – ideal for relaxing or entertaining.',
        'Discover practical and flexible layouts designed to suit your lifestyle.',
        'Perfectly positioned, you’re just moments from Massey University, Albany Basin, top shopping and dining, beautiful parks, and with unrivalled motorway access in every direction.',
        'Whether you’re a first-home buyer ready to embark on your next chapter, a busy professional seeking a stylish lock-up-and-leave residence, or a discerning investor looking for long-term value in a prime location – this is an opportunity not to be missed.',
        'Be among the first to experience the exceptional lifestyle these homes have to offer. Your new home awaits.',
      ],
      features: ['4 Bedrooms', '3 Bathrooms', '1 Garage', 'New build', 'Spacious, light-filled interiors'],
      highlights: [
        '3 or 4 generous double bedrooms plus a dedicated study (ideal as a 4th bedroom)',
        '3 or 3.5 stylish bathrooms, including one or two master ensuites',
        'Stunning designer kitchen for the ultimate entertaining experience',
        'Expansive open-plan living area and modern kitchen with high-quality appliances',
        'Internally accessed single garage',
      ],
      openHomes: [
        {
          day: 'Saturday',
          time: '4:30am - 5:00am',
          date: '07 Feb',
        },
        {
          day: 'Sunday',
          time: '4:30am - 5:00am',
          date: '08 Feb',
        },
      ],
      marketInsights: {
        heading: 'Albany insights',
        period: 'Last 12 months',
        medianSalePrice: '$1,067,000',
        medianChange: '↑ 10.0 %',
        activeListings: '153',
      },
      schools: [
        {
          name: 'Albany School',
          distance: '0.26km away',
          type: 'Co-Educational',
          zoning: 'State',
          zoneStatus: 'In zone',
        },
        {
          name: 'Pinehill School (Browns Bay)',
          distance: '2.50km away',
          type: 'Co-Educational',
          zoning: 'State',
          zoneStatus: 'Out of zone',
        },
        {
          name: 'Oteha Valley School',
          distance: '3.04km away',
          type: 'Co-Educational',
          zoning: 'State',
          zoneStatus: 'Out of zone',
        },
      ],
      imageUrl: '/images/b28854a7f1b2ffa2faac0c26892ba9fb.crop.2880x.webp',
      images: [
        '/images/b28854a7f1b2ffa2faac0c26892ba9fb.crop.2880x.webp',
        '/images/d3725afcb8b2f4182a4ae9c01446cdbe.crop.2880x.webp',
        '/images/8503580c5f0473eef00281c1af97af01.crop.2880x.webp',
        '/images/3ec4ac340274786f68c42d633fca399f.crop.2880x.webp',
        '/images/1233faa306d1af19786adc79ab533642.crop.2880x.webp',
        '/images/2d6783af699a91af287a232a3d7821fa.crop.2880x.webp',
      ],
    },
    {
      id: '32a-okains-bay-road-robinsons-bay',
      type: 'residential',
      title: '32A Okains Bay Road, Robinsons Bay',
      location: 'Robinsons Bay, Banks Peninsula',
      priceRange: 'NZD $950,000',
      bedrooms: '4',
      bathrooms: '2',
      garage: '2',
      landArea: '782m²',
      titleType: 'Freehold',
      listingNumber: 'ST9398',
      listingDate: '16 January',
      propertyFilesUrl: 'https://www.propertyfiles.co.nz/property/32OkainsBayRd',
      description:
        'Tucked into the heart of Robinsons Bay and featuring breathtaking views over the Peninsula, this 2000s-built, builder\'s own home delivers the kind of solid, practical bach that\'s made for generations to cherish.',
      details: [
        'Set on a 782m² freehold section, the main home offers three bedrooms and a family bathroom with a separate bath and shower, while the accommodation is cleverly extended by a carpeted double garage with a substantial, connected and private oversized bedroom with its own kitchenette and ensuite.',
        'Character and comfort are front and center, with exposed Rimu framing throughout, full double glazing, and a living space that truly impresses.',
        'Cathedral ceilings are met with breathtaking bay views and a log burner combines with a heat pump for effortless year-round comfort.',
        'Multiple sliders open from the living area to several outdoor decks, creating natural indoor-outdoor flow and giving you options to chase the sun, entertain, or simply sit back and take in the outlook.',
        'The spacious, family-friendly kitchen sits at the heart of the home, offering plenty of bench space, great storage and a warm, social layout - imagine cooking, chatting and making family meals come to life all whilst enjoying the bay as your backdrop.',
        'Low-maintenance grounds mean more time exploring and less time maintaining, with a garden shed, off-street parking and space for all the bach toys.',
        'Just minutes from French Farm Winery, a short drive into Akaroa, and surrounded by bays, beaches and walking tracks, this is a genuine family bach - warm, well-built and perfectly positioned for years of memories still to come.',
        'Please be aware that this information may have been sourced from REINZ/Property Smarts/Land Information New Zealand/the relevant local authority/CERA and we have not been able to verify the accuracy of the same.',
      ],
      features: ['4 Bedrooms', '2 Bathrooms', '2 Garages', '782m² Land area', 'Breathtaking views over the Peninsula'],
      highlights: [
        'Exposed Rimu framing and double glazing throughout',
        'Cathedral ceilings and large living area with bay views',
        'Log burner plus heat pump for year-round comfort',
        'Oversized guest suite with kitchenette and ensuite',
        'Minutes to French Farm Winery and Akaroa',
      ],
      openHomes: [
        {
          day: 'Sunday',
          time: '8:30am - 9:30am',
          date: '08 Feb',
        },
      ],
      additionalFeatures: [
        '4 other parks',
        '2 Separate toilets',
        'Rates: $4,761.74 per annum',
      ],
      marketEstimate: {
        heading: 'Realestate.co.nz Market Insights',
        subheading: 'What you can expect to pay for this property',
        low: '$871K',
        med: '$949K',
        high: '$1.01M',
        capitalValue: '$910,000',
        capitalValueDate: '1 Aug 2022',
      },
      capitalValueBreakdown: {
        landValue: '$205,000',
        improvementValue: '$705,000',
      },
      propertyHistory: [
        {
          date: '16 Jan 2026',
          event: 'For sale',
          price: '$950,000',
          daysOnMarket: '19 days on the market',
        },
        {
          date: '1 Aug 2022',
          event: 'CV update',
          price: '$910,000',
        },
        {
          date: '23 Nov 2019',
          event: 'CV update',
          price: '$590,000',
        },
        {
          date: '16 Sep 2014',
          event: 'Sold',
          price: '$545,000',
        },
      ],
      imageUrl: '/images/c6668339bcef3ecb2591716f878bd8ba.crop.2880x.webp',
      images: [
        '/images/c6668339bcef3ecb2591716f878bd8ba.crop.2880x.webp',
        '/images/a425529dfa9cf4a2f7dd12676859111f.crop.2880x.webp',
        '/images/88204dbad9994439f5ae0ded761fbc32.crop.2880x.webp',
        '/images/88d71afe62c5de9b7de0c577908832be.crop.2880x.webp',
        '/images/52ad24887ebf3cd822abf1b99b037e25.crop.2880x.webp',
        '/images/3aed4e6f8516106efe6ab93a8778070a.crop.2880x.webp',
      ],
    },
  ],
  commercial: [
    {
      id: 'boutique-tourist-accommodation-west-coast',
      type: 'commercial',
      title: 'Boutique Tourist Accommodation West Coast',
      location: 'West Coast, Greymouth',
      priceRange: 'NZD $1,250,000 + GST (if any)',
      landArea: '2ha',
      titleType: 'Freehold',
      listingNumber: 'WC9391',
      listingDate: '3 February',
      description:
        'Goldfields Suites. On offer here is a rather unique Qualmark Gold adults only boutique accommodation business, set in a lovely 2-hectare bush setting just 10 minutes\' drive from Greymouth.',
      details: [
        'Aimed at the luxury market, the property provides a unique experience for the discerning traveller.',
        'Currently operated just 6 months of the year, with many unique points of difference, potential here to expand the business or just enjoy the lifestyle.',
        'A separate two-bedroom managers apartment completes the picture.',
        'Make an enquiry today to start your new lifestyle.',
      ],
      features: ['Qualmark Gold', 'Adults only boutique accommodation', '2ha bush setting', '10 minutes to Greymouth'],
      highlights: [
        'Qualmark Gold adults-only accommodation experience',
        '2-hectare bush setting with premium positioning',
        'Lifestyle business with expansion potential',
        'Separate two-bedroom managers apartment',
      ],
      imageUrl: '/images/566825f762c1c118cee05bcaa908bcd7.crop.1660x948.webp',
      images: [
        '/images/566825f762c1c118cee05bcaa908bcd7.crop.1660x948.webp',
        '/images/f9ad07d9959daecb60021a924cb00a49.crop.2880x.webp',
        '/images/bc053a58e6497f3b73ff75a4d2906aeb.crop.2880x.webp',
        '/images/685f5aa718e219579c0a54066d0846f0.crop.420x230.webp',
        '/images/70b40d564f98c329b8d2f09d1747afe7.crop.420x230.webp',
        '/images/53b4a9e8c7a055dee1a873a12666f289.crop.2880x.webp',
        '/images/12e421f52c12218f6112c14df103feea.crop.420x230.webp',
      ],
    },
    {
      id: '277-thames-st-oamaru',
      type: 'commercial',
      title: 'Ticks the Boxes! Attractive Commercial Investment!',
      location: '277 Thames Street, Oamaru',
      priceRange: 'Deadline Sale',
      floorArea: '220m²',
      landArea: '1012m²',
      listingNumber: '67038244',
      listingDate: '31 January',
      deadlineSale: {
        day: 'Wednesday',
        time: '4:00pm',
        date: '04 Mar',
      },
      description:
        '277 Thames Street, Oamaru represents a rare opportunity to purchase a tidy tenanted investment property, well located on the main arterial route (SH1) through Oamaru.',
      details: [
        'Set on an approx. 1,012sqm (more or less) site, is a very well presented approx. 220sqm (approx.) office building, well fit-out inside.',
        'The property is tenanted by the established local business Aqus Limited, a rural services company servicing the wider Waitaki rural sector.',
        'Aqus Limited have recently committed to a renewed five (5) year term, with right of renewal thereafter.',
        'The property is for genuine sale, so if you want to add a very tidy property to your investment portfolio - act fast.',
        'For Sale by way of Deadline Private Treaty, closing Wednesday 4th March 2026 at 4pm (unless sold prior).',
      ],
      features: ['Approx. 220m² office building', 'Approx. 1012m² site', 'SH1 arterial route', 'Tenanted investment'],
      highlights: [
        'Established tenant with renewed 5-year term',
        'Prime SH1 arterial route location',
        'Tidy, well-presented office fit-out',
        'Investment-grade commercial property',
      ],
      imageUrl: '/images/prop2/13f47d7a8f0fc89abcceac32708c6ba0.crop.2880x.webp',
      images: [
        '/images/prop2/13f47d7a8f0fc89abcceac32708c6ba0.crop.2880x.webp',
        '/images/prop2/462ff7c5424a08c76d656a9c30c7b4f8.crop.1660x948.webp',
        '/images/prop2/58495ad1f9b47c427132e718348accf0.crop.420x230.webp',
        '/images/prop2/5d748be01ff5e3f78c2b6becd775733f.crop.420x230.webp',
        '/images/prop2/8715ca3ca0334004234cd433b066a1a6.crop.2880x.webp',
        '/images/prop2/90e94544d0b2237f2deff5a7a56552ee.crop.2880x.webp',
        '/images/prop2/c27f99e459c08af918fb3f0f84b1a9c4.crop.2880x.webp',
        '/images/prop2/eed922b7fbe84093b35f11d9136eb558.crop.2880x.webp',
        '/images/prop2/f469213a1b5ca3898c450778f4e51928.crop.420x230.webp',
      ],
    },
  ],
  industrial: [
    {
      id: '83-87-port-road-whangarei',
      type: 'industrial',
      title: 'Prominent Industrial Leasehold Site',
      location: '83-87 Port Road, Whangarei',
      priceRange: 'NZD $2,150,000',
      floorArea: '980m²',
      landArea: '1703m²',
      listingNumber: 'NW2583',
      listingDate: '18 December 2025',
      description:
        'Prominently positioned directly opposite the Okara Shopping Complex, this high-profile site offers exceptional presence and long-term development potential.',
      details: [
        'Located within the Waterfront Zone, the property benefits from flexible zoning provisions that allow for a diverse mix of uses, including residential apartments and commercial activities.',
        'Council plans provide for the continuation of the Hatea Loop walkway along the river edge to the rear of the property, enhancing connectivity, amenity and future value.',
        'Established tenants include O’Brien Plumbing and Viridian Glass, providing immediate income.',
        'The sale includes a well-performing self-storage business comprising 18 containers, currently operating at approximately 90% occupancy.',
      ],
      features: ['Waterfront Zone', 'High-profile site', 'Income-producing tenants', 'Self-storage business'],
      highlights: [
        'Opposite Okara Shopping Complex',
        'Flexible zoning with mixed-use potential',
        'Immediate income from established tenants',
        'Self-storage business with strong occupancy',
      ],
      imageUrl: '/images/ind1/15f7b318ac2f8615d944d7ba91f2f443.crop.2880x.webp',
      images: [
        '/images/ind1/15f7b318ac2f8615d944d7ba91f2f443.crop.2880x.webp',
        '/images/ind1/4750b8418c288bdee9d53e914589ca88.crop.1660x948.webp',
        '/images/ind1/89ec0fa5e773a69da2513e1153466868.crop.2880x.webp',
        '/images/ind1/0bc4ea615b8168a35b52ff9d73314f06.crop.420x230.webp',
        '/images/ind1/200a3f9c75134d3f48e38fe120046853.crop.420x230.webp',
        '/images/ind1/82de76c9cfdce5027322bee02d71b6ab.crop.420x230.webp',
      ],
    },
    {
      id: '78-delta-avenue-new-lynn',
      type: 'industrial',
      title: 'New Lynn Standalone Commercial/Industrial',
      location: '78 Delta Avenue, New Lynn',
      priceRange: 'NZD $3,750,000',
      floorArea: '720m²',
      landArea: '1261m²',
      titleType: 'Freehold',
      listingNumber: '16910560',
      listingDate: '4 February',
      deadlineSale: {
        day: 'Thursday',
        time: '2:00pm',
        date: '12 Mar',
      },
      description:
        'This unique property is situated within one of Auckland’s fastest-growing and multi-faceted suburbs and presents a compelling opportunity for add-value investors, owner-occupiers, and developers.',
      details: [
        'Excellent road frontage, parking and rear yard with separate access.',
        'Located within an established and tightly held Auckland mixed-use industrial environment.',
        'Existing improvements and Business – Light Industry zoning provides a range of repositioning or redevelopment opportunities.',
        '1,261sqm (more or less) freehold site in the established New Lynn commercial precinct.',
        'Improvements comprise two buildings, including a flexible 540 sqm clear-span factory/warehouse with office/amenities, dual roller door access, and a rear building of 180sqm, plus yard area.',
        'Rear building currently leased on a month-by-month basis, providing holding income of $2,300 per month (GST inclusive).',
        'Offered for sale by tender, closing 2pm, 12 March 2026, unless sold prior.',
      ],
      features: ['Standalone industrial property', 'Business – Light Industry zoning', 'Rear yard access'],
      highlights: [
        'Standalone freehold industrial holding',
        'Add-value potential in tightly held location',
        'Holding income with flexible lease',
        'Strong fundamentals and location appeal',
      ],
      imageUrl: '/images/ind2/427ca5fd8edf57c04488b880e424daff.crop.2880x.webp',
      images: [
        '/images/ind2/427ca5fd8edf57c04488b880e424daff.crop.2880x.webp',
        '/images/ind2/5648ffdf5293b0ef3cb244bb89f26a80.crop.2880x.webp',
        '/images/ind2/982474ad39ada77bc058deb42e225ef8.crop.2880x.webp',
        '/images/ind2/3ab6065296bacedc4aac6f0b82497c9a.crop.1660x948.webp',
        '/images/ind2/677b473f7b99e8d5d81a7278c6a5d2df.crop.420x230.webp',
        '/images/ind2/6813929e7b186a2fe24d8ccad625ae61.crop.420x230.webp',
        '/images/ind2/91859f36f8d177308313d1ad609a7eaf.crop.420x230.webp',
      ],
    },
  ],
} as const

// Update business types with image URLs
export const businessTypesWithImages = [
  {
    id: 'petrol-stations',
    name: 'Petrol Stations',
    description: 'Stable, cash-flow positive businesses with consistent demand.',
    priceRange: 'NZD $500,000 - $3,000,000+',
    suitableFor: 'Hands-on operators and passive investors',
    highlights: [
      'Consistent daily cash flow',
      'Prime location advantages',
      'Established customer base',
      'Multiple revenue streams (fuel, convenience items)',
    ],
    imageUrl: '/images/juan-fernandez-ZdzO5PgYObA-unsplash.jpg',
  },
  {
    id: 'motels',
    name: 'Motels',
    description: 'Tourism-driven hospitality businesses in prime New Zealand locations.',
    priceRange: 'NZD $800,000 - $3,500,000+',
    suitableFor: 'Hospitality entrepreneurs and tourism investors',
    highlights: [
      'Tourism industry growth',
      'Seasonal and year-round demand',
      'Property appreciation potential',
      'Diverse revenue streams',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hotels',
    name: 'Hotels',
    description: 'Premium hospitality establishments in tourist destinations.',
    priceRange: 'NZD $2,000,000 - $10,000,000+',
    suitableFor: 'Large-scale hospitality investors',
    highlights: [
      'Premium market positioning',
      'International tourism appeal',
      'Multiple revenue streams',
      'Brand value and reputation',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'restaurants',
    name: 'Restaurants',
    description: 'Culinary businesses in New Zealand\'s vibrant food scene.',
    priceRange: 'NZD $200,000 - $1,200,000+',
    suitableFor: 'Chef-entrepreneurs and hospitality enthusiasts',
    highlights: [
      'Creative business opportunities',
      'Strong local food culture',
      'Tourism and local customer base',
      'Brand building potential',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'liquor-stores',
    name: 'Liquor Stores',
    description: 'Profitable retail businesses with strong local market presence.',
    priceRange: 'NZD $300,000 - $1,500,000+',
    suitableFor: 'Retail operators and local business investors',
    highlights: [
      'High-margin products',
      'Local community focus',
      'Regulated market stability',
      'Established supplier relationships',
    ],
    imageUrl: '/images/stephen-ventura-aocMmIyGs_A-unsplash.jpg',
  },
  {
    id: 'glass-stores',
    name: 'Glass Stores',
    description: 'Specialized retail and service businesses in glass products.',
    priceRange: 'NZD $250,000 - $1,000,000+',
    suitableFor: 'Trade-focused operators and service businesses',
    highlights: [
      'Specialized market niche',
      'Trade and retail customers',
      'Service and product sales',
      'Established trade relationships',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'kiwi-avocado-farms',
    name: 'Kiwi & Avocado Farms',
    description: 'Agricultural investments in New Zealand\'s premium export crops.',
    priceRange: 'NZD $1,000,000 - $10,000,000+',
    suitableFor: 'Agricultural investors and export-focused businesses',
    highlights: [
      'Export market opportunities',
      'Premium product positioning',
      'Long-term asset appreciation',
      'Sustainable farming practices',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bars-gaming',
    name: 'Bars & Gaming',
    description: 'Entertainment venues with gaming and hospitality revenue.',
    priceRange: 'NZD $600,000 - $2,500,000+',
    suitableFor: 'Hospitality operators with gaming experience',
    highlights: [
      'Dual revenue streams',
      'Evening and night trade',
      'Gaming license value',
      'Entertainment industry growth',
    ],
    imageUrl: '/images/catcap-XMGGh7fsxP8-unsplash.jpg',
  },
  {
    id: 'grocery-stores',
    name: 'Grocery Stores',
    description: 'Essential retail businesses serving local communities.',
    priceRange: 'NZD $400,000 - $2,500,000+',
    suitableFor: 'Retail operators and community-focused investors',
    highlights: [
      'Essential service business',
      'Consistent customer traffic',
      'Diverse product range',
      'Community integration opportunities',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'salons',
    name: 'Salons',
    description: 'Beauty and personal care businesses serving local communities.',
    priceRange: 'NZD $150,000 - $800,000+',
    suitableFor: 'Beauty professionals and service business operators',
    highlights: [
      'Personal service business',
      'Recurring customer base',
      'Creative business environment',
      'Community-focused operations',
    ],
    imageUrl: '/images/adam-winger-VjRpkGtS55w-unsplash.jpg',
  },
]

